### ISSUE TITLE
使用github-action被封的情况有遇到过吗？

### ISSUE THREAD

**Issue by Nauxscript** [x-cold/yuque-hexo#98]
前阵子按照前人分享的博客搭建 语雀 + yuque-hoxo + github-action 的workflow，结果封了我好几个小号，后来和客服交涉了好久，难顶，不知道大家有没有遇到这种情况？

![image](https://user-images.githubusercontent.com/13010589/145783714-ed1daf95-0e71-421a-bdb7-b26c4c2de58d.png)

这是客服的回复

**Comment by x-cold** [comment]
没有遇到过，你的 workflow 有其他任务吗

**Comment by Nauxscript** [comment]
没有，就如大部分人分享出来的使用方法
workflow 内容如下：

```yml
name: Deploy Blog

on: [push] # 当有新push时运行

jobs:
  build: # 一项叫做build的任务

    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    
    steps:
    - name: Checkout # 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v2 # 脚本来自 https://github.com/actions/checkout
      
    - name: Use Node.js 16.x # 配置Node环境
      uses: actions/setup-node@v2 # 配置脚本来自 https://github.com/actions/setup-node
      with:
        node-version: "16.x"
    
    - name: Install dependencies
      run: |
        # install dependencies
        npm i -g hexo-cli # 安装hexo
        npm i -g yuque-hexo # 安装语雀hexo插件
        npm i
  
    - name: Deploy
      env:
        YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
      run: |
        # publish
        npm run sync # 执行部署程序
```
原本后面还有一步是获取了最新的语雀文章后进行hexo generate 然后把生产文件夹 dist 推到另外一个专门部署 github page 的仓库下的，那样写就导致我现在的号封了，为了排查是哪一步违规，我把最后那一步删除后，即剩下上面那部分内容，然后进行github action的测试，结果把另外一个小号也封了；

就很纳闷
